### ISSUE TITLE
Update and challenges on migrating sources

### ISSUE THREAD

**Issue by jwhendy** [ros-melodic-arch/ros-melodic-desktop#1]
It's been some time and I finally got time to work on this again. I've made pretty good progress updating the PKGBUILDs for almost all the packages. I posted my hacky script [here](https://gist.github.com/jwhendy/49ba67c4f13f4fdca36f12fd03ab0f9c) if you want to take a look.

Since these aren't pushed, I had to build from my local directories, and just build ros-melodic-desktop from the updated urls. Here's a few issues I haven't solved programmatically.

- [x] some github downloads have a prefix in front of `${pkgver}`, so for most it's `github.com/owner/repo/archive/${pkgver}.tar.gz`. However some like [orocos_kdl](https://api.github.com/repos/orocos/orocos_kinematics_dynamics/tags) and [rviz](https://api.github.com/repos/ros-visualization/rviz/tags) preface the file with `v-` or `visualization-`.
- [x] on the note above, I was trying to figure out the latest package via api.github, but this requires figuring out if `0.x` or `1.x` is ROS1 vs. ROS2. Also, even by doing that, sometimes the tag names are `foo-x.y.z` and it might not happen, but one might want `v1.2.3` but there might be a `beta1.2.3` and it's not easy to figure out which pre-words are OK and which are not desired.

- [x] I had troubles build `ros-melodic-tf-conversions`. It kept expecting `/opt/ros/melodic/lib/liborocos_kdl.so.1.3.0` even though I had 1.4.0 installed. I'm hoping this was some cached dep, but I never did solve it except by symlinking 1.4.0 to a fake 1.3.0 just to build that package. It never came up again.

- [x] using the [distribution.yaml](https://raw.githubusercontent.com/ros/rosdistro/master/melodic/distribution.yaml) for melodic, you can tell if a package is a meta or not by whether or not it has other packages listed. I thought if it was a singular package, `_dir` should just be `pkg-${pkgver}` where `pkg` is the ROS pkg name. Some packages, though, end up in `pkg-${pkgver}/repo` when unpacked. I changed those manually.

- [x] it got too complicated to deal with any packages having multiple `sources=` entries, so I ignored those packages.

Overall, I think a way to programmatically generate all `PKGBUILD` files would be the best, including storing the settings and any scripts necessary for each.

I'm pretty confident in pushing at least the `ros-melodic-desktop` packages and think I may just do all of them, unless there are objections. I think there will be a few glitches, but it's pretty hard to quickly troubleshoot via local dirs vs. `aur sync`. Let me know what you think.

**Comment by bionade24** [comment]
I saw this now, thanks for showing me your script. I currently work on some kind of CD for updating, building and delivering packages. I have the same edge-case-problems like you, and I think even if we hardcode things, there will be around 5% packages where things changed and it needs manual intervention. So I would simply fix the broken builds manually, and maybe make hardcoded exceptions for this package. The Overall advantage is that I need a repo for the clean builds, so afterwards people (who trust me) can directly add me repo and don't need to compile their own. Altogether ROS is really messy, and if they don't change things with ROS2, we would never get packages in the official repos.

**Comment by jwhendy** [comment]
I'm going through and pushing everything I've updated as we speak, so maybe wait until end of today or tomorrow and then see what's left? I would hate to duplicate efforts!

With the pushes I'm currently making, we should have everything in `ros-melodic-ros-base`, `ros-melodic-desktop`, and `ros-melodic-desktop-full` to the following:
- updated to official github sources where they exist (I'm ignoring bitbucket and others for now)
- versions matching whatever is listed for `melodic` on [ros index](https://index.ros.org/)
- unified `_dir`
- updated `sha256sums`

I'll post the list of edge cases when I'm done. I don't want to push unless I know they build, so that's what I'm currently doing locally first.

**Comment by bionade24** [comment]
No problem, I focus currently on the CD and make it less hacky. Hope your script fixes most packages and we have ros working without millions of patches.

**Comment by jwhendy** [comment]
Hmmm. As I'm pushing these, there are a few variations going on:

- master is unchanged based on my script (do nothing)
- version has changed, but sources were already updated (`pkgver` will change)
- migrating from `ros-gbp` to upstream, same version (only `sources` are changing)
- some combination of the above

In the case of ros-gbp -> upstream sources but same version... do I need to bump `pkgrel` so that an update is triggered from AUR? Or will it detect a diff anyway and flag for update?

I'm not sure how many I've already pushed with updated sources, but same pkgver/pkgrel. It shouldn't be too many though.

**Comment by jwhendy** [comment]
Update to issues above (marking resolved):

- file prefixes on github downloads: thankfully once the few were fixed, we don't have to mess with them again as only `pkgver` changes. Thinking this is so rare it's not worth thinking about further.

- latest package: I gave up and just scraped rosindex instead. It's easier to get per-distribution from there, and that's the official list of info already maintained. I chose to just use the version from there and it worked great on all `ros-melodic-desktop` packages (and `ros-melodic-ros-base`)

- I don't know what happened with `tf_conversions`. I uninstalled everything and cleaned pacman cache to ensure all was building well today. I built all of ros-base and ros-desktop. No problems with versioned libraries this time.

- packages where the unpacked tarball uses `repo-pkgver/repo` as the dir: I treated this like the prefixed filenames. Once we know and adjust the `PKGBUILD`, it shouldn't change again.

- parsing sha256sums is still challenging if we have multiple sources. So far, this is not many packages (<10 I think) so maybe it doesn't matter. Leaving that unresolved for now.

I need to hunt down a couple of ros-gbp packages I updated before I caught that I needed to bump the pkgrel. Other than that, all of ros-melodic-desktop should be good to go on upstream now. I caught a few additional packages from ros-melodic-ros-base as well.

**Comment by jwhendy** [comment]
@bionade24 one quick question: can you remind me on the update frequency of this github repo -> AUR? Wondering how long it will be before all of `ros-melodic-desktop` in AUR has the changes I pushed.

There may be a few warnings here and there as I didn't initially catch the `pkgrel`. I believe I've now fixed all of those. Approach:

- if the `pkgver` increased when updating to upstream sources, `pkgrel=0`
- if the `pkgver` stayed the same, `pkgver+=1`

**Comment by bionade24** [comment]
Seems amazing. It's not already in the AUR because I have a daily cronjob. I stop this until we have fixed all `pkgrel`s, because you can't force-push to AUR.

**Comment by bionade24** [comment]
`pkgrel` start at 1, not at 0.

**Comment by bionade24** [comment]
I will stop this cronjob now and try to build everything, and only push successfully built packages to AUR. Maybe it'll take 2 days, I don't have that much time at the moment.

**Comment by jwhendy** [comment]
>pkgrel start at 1, not at 0.

Noooooooooooooooo. Damnit. Ok, I should be able to script this. I chose to push force here with these small fixes. I can not do this if you prefer.

Thankfully this should be pretty easy. The `pkgrel` only went to `0` when the `pkgver` increased, so I just need to find all instances of `pkgrel=0` and update, then commit and push. I'll post back when this is done.

**Comment by jwhendy** [comment]
Confirming that all `ros-melodic-ros-base`, `ros-melodic-desktop`, and `ros-melodic-desktop-full` packages should be up to date on upstream sources and now have fixed `pkgrel` where it was 0.

I'd go for the sync, and then we can catch the _hopefully_ minor issues I created :) 

Want to post back when you do this, and I'll then attempt to build directly from AUR?

**Comment by bionade24** [comment]
Sorry, but I won't sync now and do this tomorrow or Wednesday, when I finished the minor issues with my CD and it works like I want. Then I'll have prebuilt binaries for all packages in my repo, too.

**Comment by jwhendy** [comment]
No rush at all. Just want to try building from AUR as soon as they sync to catch issues early. Thanks!

**Comment by bionade24** [comment]
I'll get all output from the clean builds in my CI and only the successfully built packages get pushed, so I'll catch everything and in case the problem is bigger I'll send you the ouput.

**Comment by jwhendy** [comment]
Ooh, that sounds even better. Indeed, if you see any oddities, let me know the packages. In particular, I'm worried a few glitches in pkgver or pkgrel might have slipped through. This will be tougher to catch as it might be someone with a version already installed and the pkgver doesn't trigger a sync tool to see it.

Anyway, it's mostly minor things. Other than that, I built them all myself so I know they at least build!
