### ISSUE TITLE
Boost version 1.72

### ISSUE THREAD

**Issue by EmbersArc** [ros-melodic-arch/ros-melodic-desktop#3]
Recently, Arch updated its boost version from 1.71 to 1.72. ROS seems to depend on 1.71 and now my ROS binaries and catkin builds don't work anymore. Is there anything I can do to fix this?

**Comment by acxz** [comment]
The way to fix this would be to completely rebuild and reinstall the ROS packages. I would first remove all ros-melodic-* packages from your system (also make sure to remove the build directories for them, such as `rm -rf ~/.cache/yay/ros-melodic-*`) and then rebuild/reinstall them (`yay -Syu ros-melodic-desktop-full`).
It is inconvenient for now but we are working on getting prebuilt binaries out through Arch4Edu.

**Comment by acxz** [comment]
@EmbersArc TLDR:

`yay -Rns $(yay -Qsq ros-melodic)`
`rm -rf ~/.cache/yay/ros-melodic-*`
`yay -Syu ros-melodic-desktop`

Please let us know if this does not work.

**Comment by EmbersArc** [comment]
This seems to have worked. At least I'm back to having issues with the Python version, but I somehow managed to fix that last time. Thanks a lot for your help and for maintaining this. And good luck with the prebuilt binaries, I will be waiting patiently.

**Comment by acxz** [comment]
Sweet! Feel free to ask about your python issues as well (in another issue) we can prob help with that as well.
