### ISSUE TITLE
Attempt to use your repository fails to download ros-melodic-tf2-kdl-0

### ISSUE THREAD

**Issue by t3pfaffe** [ros-melodic-arch/ros-melodic-desktop#4]
Running a pacman -S ros-melodic-desktop fails with this message: 

```
error: failed retrieving file 'ros-melodic-tf2-kdl-0.6.5-2-any.pkg.tar.zst' from repo.oscloud.info : Maximum file size exceeded
warning: failed to retrieve some files
```

**Comment by RobertoBochet** [comment]
I am receiving the same error also with the file `ros-melodic-rviz-1.13.7-3-x86_64.pkg.tar.zst`

**Comment by bionade24** [comment]
Yes

> Running a pacman -S ros-melodic-desktop fails with this message:
> 
> ```
> error: failed retrieving file 'ros-melodic-tf2-kdl-0.6.5-2-any.pkg.tar.zst' from repo.oscloud.info : Maximum file size exceeded
> warning: failed to retrieve some files
> ```

Will look into it.

**Comment by bionade24** [comment]
> I am receiving the same error also with the file `ros-melodic-rviz-1.13.7-3-x86_64.pkg.tar.zst`

I'm aware of this, but I need to recompile everything linking to OGRE so for now please compile rviz yourself, then it will work.

**Comment by bionade24** [comment]
Closing this as already was fixed long  ago. Current issue are already fixed, they changed some build path names internally and so my CI couldn't rebuild the index anymore.
