### ISSUE TITLE
catkin_make complains that empy python module is not installed

### ISSUE THREAD

**Issue by zuntik** [ros-melodic-arch/ros-melodic-desktop#5]
```
CMake Error at /opt/ros/melodic/share/catkin/cmake/empy.cmake:29 (message):
  Unable to find either executable 'empy' or Python module 'em'...  try
  installing the package 'python-empy'
```
However python-empy package is installed

**Comment by acxz** [comment]
Can you post the command you used to receive this error? Also make sure you follow the ROS wiki: https://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment

Note running catkin_make with python3

**Comment by acxz** [comment]
Closing this issue since @zuntik has been unresponsive for more than a week, feel free to open this issue up again if you still encountering issues.
